name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: sudo apt install git; sudo sh ./dependencies.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

