name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: sudo apt install git; sudo -E sh ./dependencies.sh
    - name: Build
      run: export OPENNI2_REDIST="/lib/libOpenNI2"; export OPENNI2_REDIST64="/lib/libOpenNI2"; cargo build --verbose
